
export const darkYellow = '#d1bb7d'
export const sweetPink = '#ad8e9e'
export const lightYellow = '#ffffad'
export const interactiveBlue = '#007AFF'
export const darkBlueShade = '#2e4e6b'
export const lightBlueSky = '#adf5ff'
export const greyBlue = '#abd3d9'
export const darkyBlue = '#236d78'
export const lightyBlue = '#44adbd'
